import { StyleSheet, Dimensions } from 'react-native'
import { Colors } from '../../../Assets/Themes'

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.pureBG,
    },
    input: {
        borderRadius: 5,
        marginTop: height * .05,
        alignSelf: 'center',
        alignItems: 'flex-start',
        height: height / 16,
        width: width - 50,
    },
    button: {
        backgroundColor: Colors.mainBG,
        marginTop: height * .05,
        width: width - 50,
        height: height / 14,
        alignContent: 'center',
        justifyContent: 'center',
        elevation: 2,
        borderRadius: width / 35,
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
    },
    smallBtn: {
        padding: 0,
        marginRight: -15,
    },
    proImage: {
        backgroundColor: Colors.mainBG,
        width: width / 3,
        height: width / 3,
        alignContent: 'center',
        justifyContent: 'center',
        elevation: 2,
        borderRadius: width / 35,
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
    },
    Pimg: {
        width: width / 3.1,
        height: width / 3.1,
        borderRadius: width / 35,
    },
    inputStyle: {
        color: Colors.pureTxt,
        fontSize: width / 25,
        fontFamily: 'Roboto',
    },
    inputPicker: {
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        padding: 2,
        width: width / 1.23,
    },
    customInput: {
        color: Colors.pureTxt,
        fontSize: width / 25,
        width: width / 1.8,
        fontWeight: '100',
        fontFamily: 'Roboto',
    },
    CustomLabel: {
        alignSelf: 'center',
        marginTop: height * .05,
        flexDirection: 'column',
        alignItems: 'stretch',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: Colors.mainTxt,
        width: width / 1.23,
    },
    buttonText: {
        color: Colors.pureTxt,
        fontSize: width / 25,
        fontWeight: 'bold',
        fontFamily: 'Roboto',
    },
    texterr: {
        color: Colors.red,
        fontFamily: 'Roboto_medium',
        marginLeft: width * .07,
    },
    ilabel: {
        marginLeft: height * .08,
        flex: 1,
        flexDirection: 'row',
        marginTop: height * .04,
        fontFamily: 'Roboto',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: width / 1.2,
        alignSelf: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    radioText: {
        fontFamily: 'Roboto',
        color: Colors.pureTxt,
        textTransform: 'uppercase',
        fontSize: width / 20
    },
    circle: {
        height: 24,
        width: 24,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: Colors.mainTxt,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkedCircle: {
        height: 24,
        width: 24,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: Colors.secondary,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "transparent",
    },
    selectContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderRadius: 20,
        width: width / 3,
        elevation: 1,
        backgroundColor: Colors.mainBG,
        alignSelf: 'flex-end',
        alignItems: 'center',
        marginBottom: 10,
    },
    selectText: {
        fontFamily: 'Roboto_medium',
        paddingHorizontal: 10,
        color: Colors.mainTxt,
        textTransform: 'uppercase',
        fontSize: width / 35
    },
    selectCircle: {
        height: 28,
        width: 28,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: Colors.pureBG,
        backgroundColor: Colors.pureBG,
        margin: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectCheckedCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.pureBG,
    },
    bottomModal: {
        position: 'relative',
        backgroundColor: Colors.pureBG,
        elevation: 3,
        bottom: 0,
        left: 0,
        right: 0,
    },
    checkoutSide: {
        flexDirection: 'row',
        alignSelf: 'center',
        width: width - 70,
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: height * .05,
    },
    amount: {
        flexDirection: 'column',
    },
    amountTitle: {
        fontSize: width / 40,
        color: Colors.mainTxt,
        textTransform: 'uppercase'
    },
    Tamount: {
        fontWeight: 'bold',
        color: Colors.pureTxt,
        textTransform: 'uppercase'
    },
    btnCheckout: {
        backgroundColor: Colors.mainBG,
        width: width / 3,
        height: height / 18,
        alignContent: 'center',
        justifyContent: 'center',
        elevation: 1,
        borderRadius: width / 50,
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
    },
    topTitle: {
        color: Colors.secondary,
        fontSize: width / 30,
        marginVertical: 5,
        alignSelf: 'center',
        textTransform: 'uppercase'
    },
    picker: {
        borderRadius: 5,
        marginLeft: width / 5,
        marginRight: width / 5,
        height: 40,
        borderTopWidth: 1,
        borderTopColor: Colors.mainTxt,
        borderRightWidth: 1,
        borderRightColor: Colors.mainTxt,
        borderLeftWidth: 1,
        borderLeftColor: Colors.mainTxt,
        borderBottomWidth: 1,
        borderBottomColor: Colors.mainTxt,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        color: Colors.pureTxt,
        fontSize: width / 30,
        fontFamily: 'Roboto_medium',
    },
    label: {
        marginLeft: height * .02,
        fontSize: width / 20,
        color: Colors.mainTxt,
        fontFamily: 'Roboto',
    },
    inputLabel: {
        fontSize: width / 30,
        color: Colors.pureTxt,
        textTransform: "uppercase",
        fontFamily: 'Roboto_medium',
    },
    tLabel: {
        fontSize: width / 20,
        opacity: .7,
        color: Colors.mainTxt,
        fontFamily: 'Roboto_medium',
    }
});
export default styles;